name: .NET Core

on:
  release:
    types: [published]

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - name: Pack
        run: dotnet pack src/LogAnalytics.Collector.fsproj --configuration Release -p:Version=${{ github.ref }} -p:PackageVersion=${{ github.ref }}
